---

version: '3.1'

networks:
  backend:
    driver: bridge

services:
  db:
    container_name: smart-garden-db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=test
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - backend

  app:
    container_name: smart-garden-service
    build:
      args:
        SECRET_KEY: "test"
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - backend

...
