---

version: '3.1'

networks:
  backend:
    driver: bridge

services:
  db:
    container_name: smart-garden-db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
      - ./scripts/sql:/docker-entrypoint-initdb.d/
    networks:
      - backend

  app:
    container_name: smart-garden-service
    build:
      args:
        SECRET_KEY: ${SECRET_KEY}
        ENV_TYPE: ${ENV_TYPE}
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE_NAME=${MYSQL_DATABASE_NAME}
      - MYSQL_DB_HOSTNAME=${MYSQL_DB_HOSTNAME}
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - backend

...
