name: CI

on:
  push:
    branches:
      - main

env:
  MINIMUM_COVERAGE: 75

jobs:
  check_compose_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check docker-compose file
        run: docker-compose --env-file .env.dbg up --dry-run

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # TODO: remove this
      - name: Install dependencies
        run: pip3 install pylint

      - name: Lint the code
        run: pylint app/*

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # TODO: remove this
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install -r tests/requirements.txt

      - name: Run unit tests
        run: nose2 -c tests/nose.cfg

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # TODO: remove this
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install -r tests/requirements.txt

      - name: Run unit tests
        run: nose2 -c tests/nose.cfg

      - name: Check coverage
        run: coverage report --fail-under ${{ env.MINIMUM_COVERAGE }}
